### ISSUE TITLE
It doesn't seem to be possible to disable the CORS proxy

### ISSUE THREAD

**Issue by DoomGerbil** [sourcegraph/sourcegraph-sonarqube#10]
I've got a SonarQube instance running in a K8S cluster behind an Ingress, which I have configured to include CORS headers, like so:

`ingress.yaml`
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarqube
  namespace: sonarqube
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://url.of.private.sonarqube.instance.io"
...
```

This works, and all requests to the instance do include CORS headers now, therefore I don't require an external CORS proxy.

However, I can't seem to disable the sgdev.org proxy setting - if I don't set the value, or set it to blank, `https://cors-anywhere.sgdev.org` gets used anyway (eg Chrome records a request being sent to `https://cors-anywhere.sgdev.org/https://url.of.private.sonarqube.instance.io`).

Further, all requests that get sent through this proxy return a 403 error, so this extension just basically doesn't work.

Is there a way to switch this behavior off? Even if the proxy worked, I would very much prefer to not bounce our requests off of your proxy, especially since we don't need to do so.

Thanks!
